[package]
name = "rrev"
version = "0.1.0"
authors = ["Matthew Delaney <matthew.l.delaney@gmail.com>"]
edition = "2018"

[dependencies]
#capstone-sys = "0.6.0"
capstone = { path = "capstone" }
binload = { path = "./binload" }
