[package]
name = "capstone"
version = "0.1.0"
authors = ["Matthew Delaney <matthew.l.delaney@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capstone-sys = { path = "../capstone-sys" }
