[package]
name = "binload"
version = "0.1.0"
authors = ["Matthew Delaney <matthew.l.delaney@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
enum_primitive = "0.1.1"
