[package]
name = "capstone-sys"
version = "0.1.0"
authors = ["Matthew Delaney <matthew.l.delaney@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.51.1"
